mesh:
  - direction: x
    start: -3.141592653589793
    subDomains:
      - end: 3.141592653589793
        cells: 16
        stretchRatio: 1.0
  - direction: y
    start: -3.141592653589793
    subDomains:
      - end: 3.141592653589793
        cells: 16
        stretchRatio: 1.0

flow:
    nu: 0.01
    initialVelocity:
      - "cos(x) * sin(y)"
      - "- sin(x) * cos(y)"
    initialPressure: "- (cos(2*x) + cos(2*y)) / 4"
    boundaryConditions:
      - location: xMinus
        u: [PERIODIC, 0.0]
        v: [PERIODIC, 0.0]
      - location: xPlus
        u: [PERIODIC, 0.0]
        v: [PERIODIC, 0.0]
      - location: yMinus
        u: [PERIODIC, 0.0]
        v: [PERIODIC, 0.0]
      - location: yPlus
        u: [PERIODIC, 1.0]
        v: [PERIODIC, 0.0]

parameters:
    dt: 0.1
    startStep: 0
    nt: 1000
    nsave: 20
    nrestart: 10000
    convection: ADAMS_BASHFORTH_2
    diffusion: CRANK_NICOLSON
    velocitySolver:
      type: CPU
      config: config/velocity_solver.info
    poissonSolver:
      type: CPU
      config: config/poisson_solver.info
