c_compiler:
  - gcc

cxx_compiler:
  - gxx

target_platform:
  - linux-64

c_compiler_version:    # [linux]
  - 11.2              # [linux]

cxx_compiler_version:  # [linux]
  - 11.2              # [linux]
