# required channels: nvidia, conda-forge
{% set name = "amgx" %}
{% set version = "2.2.0" %}
{% set cuda = "11.4" %}
{% set build = "3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/nvidia/amgx
  git_rev: 6f14016e420617b4d57580f77b5a2ab4c28a162d
  git_depth: 1

build:
  number: {{ build }}
  string: cuda114_h{{ PKG_HASH }}_{{ build }}
  missing_dso_whitelist:
    - '*libcuda.so*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - make
    - cmake>=3.23

  host:
    - cuda {{ cuda }}
    - openmpi>=4.0

  run:
    - cudatoolkit={{ cuda }}
    - openmpi>=4.0

  run_constrained:
    - __cuda>=11.0
    - __glibc>=2.17

about:
  home: https://github.com/nvidia/amgx
  license: BSD-3-Clause
  license_file: LICENSE
