flow:
  nu: 0.025
  initialVelocity: [1.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
    - location: xPlus
      u: [CONVECTIVE, 1.0]
      v: [CONVECTIVE, 1.0]
    - location: yMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]

mesh:
  - direction: x
    start: -10.0
    subDomains:
      - end: -0.75
        cells: 186
        stretchRatio: 0.991332611050921
      - end: 0.75
        cells: 75
        stretchRatio: 1.0
      - end: 30.0
        cells: 301
        stretchRatio: 1.008743169398907

  - direction: y
    start: -10.0
    subDomains:
      - end: -0.75
        cells: 186
        stretchRatio: 0.991332611050921 
      - end: 0.75
        cells: 75
        stretchRatio: 1.0
      - end: 10.0
        cells: 186
        stretchRatio: 1.008743169398907

parameters:
  dt: 0.01
  startStep: 0
  nt: 2000
  nsave: 100
  nrestart: 5000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: cylinder
  file: cylinder.body

probes:
- name: probe-p
  type: VOLUME
  field: p
  viewer: hdf5
  path: probe-p.h5
  n_sum: 1000
  box:
    x: [-0.75, 0.75]
    y: [-0.75, 0.75]
