flow:
  nu: 0.005
  initialVelocity: [1.0, 0.0]
  boundaryConditions:
    - location: xMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
    - location: xPlus
      u: [CONVECTIVE, 1.0]
      v: [CONVECTIVE, 1.0]
    - location: yMinus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]
    - location: yPlus
      u: [DIRICHLET, 1.0]
      v: [DIRICHLET, 0.0]

mesh:
  - direction: x
    start: -8.0
    subDomains:
      - end: -0.6
        cells: 300
        stretchRatio: 0.9946752727237925
      - end: 0.6
        cells: 120
        stretchRatio: 1.0
      - end: 25.0
        cells: 1065
        stretchRatio: 1.0013907312908414

  - direction: y
    start: -8.0
    subDomains:
      - end: -0.6
        cells: 300
        stretchRatio: 0.9946752727237925
      - end: 0.6
        cells: 120
        stretchRatio: 1.0
      - end: 8.0
        cells: 300
        stretchRatio: 1.005353231775458

parameters:
  dt: 0.005
  startStep: 0
  nt: 40000
  nsave: 200
  nrestart: 10000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: GPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
  - type: points
    file: circle.body
