# required channels: barbagroup (or local), nvidia, conda-forge
{% set name = "amgxwrapper" %}
{% set version = "1.6.1" %}
{% set cuda = "11.4" %}
{% set build = "4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/barbagroup/amgxwrapper
  git_rev: v{{ version }}
  git_depth: 1

build:
  number: {{ build }}
  string: cuda114_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - make
    - cmake>=3.23
    - pkg-config

  host:
    - amgx 2.2.0 cuda114*
    - cuda {{ cuda }}
    - hdf5 * mpi_openmpi_*
    - openmpi>=4.0
    - petsc=3.16.6=mpi_openmpi*

  run:
    - amgx 2.2.0 cuda114*
    - cudatoolkit={{ cuda }}
    - hdf5 * mpi_openmpi_*
    - openmpi>=4.0
    - petsc=3.16.6=mpi_openmpi*

  run_constrained:
    - __cuda>=11.0
    - __glibc>=2.17

about:
  home: https://github.com/barbagroup/amgxwrapper
  license: BSD-3-Clause
  license_file: LICENSE
