# required channels: barbagroup (or local), nvidia, and conda-forge
{% set name = "petibm" %}
{% set version = "0.5.4rc1" %}
{% set cuda = "11.4" %}
{% set build = "4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/piyueh/petibm
  git_rev: b687e71f3845699c95089d55b48802278183b1c4
  git_depth: 1

build:
  number: {{ build }}
  string: cuda114_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - make
    - cmake>=3.23
    - pkg-config
    - sysroot_linux-64 >=2.17
  host:
    - cuda={{ cuda }}
    - amgxwrapper * cuda114*
    - hdf5 * mpi_openmpi_*
    - openmpi>=4.0
    - petsc=3.16.6=real_h11d90dd_100
    - yaml-cpp >=0.7
  run:
    - amgxwrapper * cuda114*
    - hdf5 * mpi_openmpi_*
    - openmpi>=4.0
    - petsc=3.16.6=real_h11d90dd_100
    - yaml-cpp >=0.7
  run_constrained:
    - __cuda>=11.0
    - __glibc>=2.17

about:
  home: https://github.com/barbagroup/petibm
  license: BSD-3-Clause
  license_file: LICENSE
